# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# test
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'thomas-hayden'
    scannerMode: 'MSBuild'
    projectKey: 'thomas-hayden_test'
    projectName: 'test'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--collect "Code Coverage"'
    projects: '**/*.csproj'

- task: puma-scan-pro-build-task@1
  inputs:
    projectPath: 'WebApplication2.sln'
    scanResultsFormat: 'html'
    outputFilename: 'PumaScanResults'
    verboseMode: true

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'

- script: |
    $text = Get-Content .\PumaScanResults.html -Raw
    Write-Host "$text"
    Write-Host "##vso[task.setvariable variable=Test;]$text"

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'thomas-hayden'
    repositoryName: '$(Build.Repository.Name)'
    comment: '$(Test)'